### ISSUE TITLE
[E::hts_open_format] Failed to open  (mapping with NGMLR, sort/index with samtools, calling with sniffles)

### ISSUE THREAD

**Issue by nbertholdpgc** [samtools/samtools#1825]
Hi all,
Just as a preface, I am very new to bioinformatics and coding and so it's more than likely there's a simple fix that I just don't know!
I have some adaptive sequencing data from ONT that I've been trying to perform a bioinformatics pipeline on. Before beginning, I merged all fastq_pass files into oneI first QC with chopper, align to the HG38 reference genome with NGMLR, then sort and index my bam files with samtools, before calling with Sniffles2. It's working fine up until the index and sniffles stage. I get a bam.bai output from indexing, but then when I go to perform calling with sniffles I get these errors: 

--2023-04-04 16:35:23--  https://github.com/fritzsedlazeck/Sniffles/blob/master/annotations/human_GRCh38_no_alt_analysis_set.trf.bed
Resolving github.com (github.com)... 20.248.137.48
Connecting to github.com (github.com)|20.248.137.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/path/to/human_GRCh38_no_alt_analysis_set.trf.bed/human_GRCh38_no_alt_analysis_set.trf.bed.31’

     0K .......... .......... .......... .......... ..........  581K
    50K .......... .......... .......... .......... .......... 1.11M
   100K .......... .......... .......... ........              91.2M=0.1s

2023-04-04 16:35:24 (1.03 MB/s) - ‘/path/to/human_GRCh38_no_alt_analysis_set.trf.bed.31’ saved [141385]

[E::hts_hopen] Failed to open file merged_fastq-indx.bam
[E::hts_open_format] Failed to open file "merged_fastq-indx.bam" : Exec format error
Running Sniffles2, build 2.0.7
  Run Mode: call_sample
  Start on: yyyy/dd/mm 00:00:00
  Working dir: /path/to/workdir
  Used command: sniffles -i /path/to/merged_fastq-indx.bam -v /path/to/merged_fastq.vcf --tandem-repeats /path/to/human_GRCh38_no_alt_analysis_set.trf.bed
==============================
Opening for reading: /path/to/merged_fastq-indx.bam
Traceback (most recent call last):
  File "/home/usr/.local/bin/sniffles", line 616, in <module>
    Sniffles2_Main(config.from_cmdline(),processes)
  File "/home/usr/.local/bin/sniffles", line 118, in Sniffles2_Main
    bam_in=pysam.AlignmentFile(config.input, config.input_mode)
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 950, in pysam.libcalignmentfile.AlignmentFile._open
OSError: [Errno 8] could not open alignment file `/path/to/merged_fastq-indx.bam`: Exec format error

Here is the code I've been running
#QC and Chopper
cd "/path/to/fastq_pass/" 
    gunzip *.fastq.gz
    cat *.fastq > merged_fastq.fastq
    gzip merged_fastq.fastq
cd /work/dir
        gunzip -c /path/to/merged_fastq.fastq.gz | /home/usr/.local/bin/chopper -q 09 -l 500 | gzip > /path/to/merged_fastq.filtered.fastq

#Alignment
wget https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz -P "/path/to/RefIndex_Hg38/"
        gunzip /path/to/RefIndex_Hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

"/home/usr/.local/bin/NGMLR/ngmlr-0.2.7/ngmlr" -t 5 -r "/path/to/RefIndex_Hg38/Homo_sapiens.GRCh38.dna.primary_assembly.fa" -q /path/to/merged_fastq.filtered.fastq -o /path/to/merged_fastq.sam --bam-fix 

cd /home/usr/.local/bin/
    ./samtools sort -l 0 -m 50G -@ 1 -o /path/to/merged_fastq.sorted.bam -O BAM /path/to/merged_fastq.sam 
    ./samtools index -b /path/to/merged_fastq.sorted.bam /path/to/merged_fastq-indx.bam -@ 1
    cd /work/dir

#Sniffles variant calling
 wget https://github.com/fritzsedlazeck/Sniffles/blob/master/annotations/human_GRCh38_no_alt_analysis_set.trf.bed -P /path/to/human_GRCh38_no_alt_analysis_set.trf.bed 
pip install sniffles
sniffles -i /path/to/merged_fastq-indx.bam -v /path/to/merged_fastq.vcf --tandem-repeats path/to/human_GRCh38_no_alt_analysis_set.trf.bed 

N.B. I am using version 1.09 of samtools because the later versions kept giving me a truncated file as [here](https://github.com/philres/ngmlr/issues/83)

Thanks!!

**Comment by nbertholdpgc** [comment]
I've posted to https://github.com/fritzsedlazeck/Sniffles! @jkbonfield thanks for the advice on using the latest samtools and filtering mapq to remove the negative values, that's stopped the file truncating and aborting when sorting; however, I'm still getting the failed to open error when attempting to run the indexed bam with sniffles :(

**Comment by jkbonfield** [comment]
Does a full samtools view on the file work?  Eg `samtools view -o /dev/null file.bam`.  If so I think we can close this as the problem is entirely within Sniffles.

**Comment by jkbonfield** [comment]
Closing as likely not a problem with samtools itself.
