### ISSUE TITLE
Running samtools on a file with an empty UMI tag in OX and RX fields causes "Error allocating memory. Aborting!"

### ISSUE THREAD

**Issue by jkmatila** [samtools/samtools#1926]
#### Are you using the latest version of [samtools](https://github.com/samtools/samtools/releases/latest) and [HTSlib](https://github.com/samtools/htslib/releases/latest)? If not, please specify.

Yes, running samtools 1.18 which is the latest at this time:
```
$ ./samtools --version
samtools 1.18
Using htslib 1.18
Copyright (C) 2023 Genome Research Ltd.

Samtools compilation details:
    Features:       build=Makefile curses=yes
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -g -Wall -O0
    LDFLAGS:
    HTSDIR:         htslib-1.18
    LIBS:
    CURSES_LIB:     -lcurses

HTSlib compilation details:
    Features:       build=Makefile libcurl=yes S3=no GCS=no libdeflate=no lzma=yes bzip2=yes plugins=no htscodecs=1.5.1
    CC:             gcc
    CPPFLAGS:
    CFLAGS:         -g -Wall -O2 -fvisibility=hidden
    LDFLAGS:        -fvisibility=hidden

HTSlib URL scheme handlers present:
    built-in:    preload, data, file
    libcurl:     imaps, pop3, http, smb, gopher, sftp, ftps, imap, smtp, smtps, rtsp, scp, ftp, telnet, mqtt, rtmp, ldap, https, ldaps, smbs, tftp, pop3s, dict
    crypt4gh-needed:     crypt4gh
    mem:         mem

```

 #### Please describe your environment.

 ```
$ uname -sr
Linux 3.10.0-862.14.4.el7.x86_64

$ gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

#### Please specify the steps taken to generate the issue, the command you are running and the relevant output.

The problem was originally observed with BAM files from a real pipeline, which for some reason have empty UMI tags in the `OX` and `RX` fields. Here is the minimal file with which I could reproduce the issue (also attached in [repro4.zip](https://github.com/samtools/samtools/files/12844643/repro4.zip)). 

```
@HD     VN:1.6  SO:coordinate
@SQ     SN:1    LN:249250621
read1   16      1       19625   0       10M     *       0       0       TCCTTGTGTG      DIIEFGGGFD      OX:Z:   RX:Z:
```

When running `samtools stats` on this file, it fails with the error message "Error allocating memory. Aborting!"

```
$ samtools repro4.sam
Error allocating memory. Aborting!
```

#### Additional information

It appears to fail on [stats.c:780](https://github.com/samtools/samtools/blob/1.18/stats.c#L780). Here's a transcript from a GDB session:

```
$ gdb samtools
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from samtools...
(gdb) break error
Breakpoint 1 at 0x6302c: error. (2 locations)
(gdb) run stats repro4.sam
Starting program: /usr/local/bin/samtools stats repro4.sam
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, error (format=0x5555556bb080 "Error allocating memory. Aborting!\n") at stats.c:2091
2091        if ( !format )
(gdb) up
#1  0x00005555555aeb17 in collect_barcode_stats (bam_line=0x55555576efe0, stats=0x555555726650) at stats.c:780
780                     error("Error allocating memory. Aborting!\n");
(gdb) where
#0  error (format=0x5555556bb080 "Error allocating memory. Aborting!\n") at stats.c:2091
#1  0x00005555555aeb17 in collect_barcode_stats (bam_line=0x55555576efe0, stats=0x555555726650) at stats.c:780
#2  0x00005555555af74d in collect_orig_read_stats (bam_line=0x55555576efe0, stats=0x555555726650, gc_count_out=0x7fffffffea24) at stats.c:970
#3  0x00005555555b04f9 in collect_stats (bam_line=0x55555576efe0, stats=0x555555726650, read_pairs=0x55555576efb0) at stats.c:1227
#4  0x00005555555b8b73 in main_stats (argc=2, argv=0x7fffffffed20) at stats.c:2585
#5  0x000055555558df4e in main (argc=3, argv=0x7fffffffed18) at bamtk.c:279
(gdb) info locals
offset = 0
barcode_tag = 0x55555576a128 "RX"
qual_tag = 0x55555576a12b "QX"
bc = 0x555555797241 "Z"
barcode = 0x555555797242 ""
barcode_len = 0
error_flag = 0
qt = 0x0
barqual = 0x0
barqual_len = 0
nbases = 0
tag = 3
i = 4
acgtno = 0x555555709550
quals = 0x555555709610
separator = 0x55555576a11c
maxqual = 0x55555576a120
(gdb)
```

**Comment by whitwham** [comment]
It looks like it is treating the realloc to size 0 as an error (understandably).  Thanks for the detailed bug report.
