### ISSUE TITLE
Segfault during merging of depthmaps

### ISSUE THREAD

**Issue by bstempi** [samtools/samtools#652]
Hi,
I'm running the latest ODM Docker image on a VPS running Debian with 24GB of RAM and 8 CPU cores.  I'm currently trying to stitch together a survey that consists of around 270 photos, totaling 1-1.5GB.  During processing, I get this:

```
2017-03-10 13:48:42,183 Cleaning depthmap for image DJI_0062.JPG
2017-03-10 13:48:43,404 Cleaning depthmap for image DJI_0021.JPG
2017-03-10 13:48:44,682 Cleaning depthmap for image DJI_0060.JPG
2017-03-10 13:48:46,072 Cleaning depthmap for image DJI_0162.JPG
2017-03-10 13:48:47,415 Cleaning depthmap for image DJI_0236.JPG
2017-03-10 13:48:52,428 Cleaning depthmap for image DJI_0050.JPG
2017-03-10 13:48:53,772 Cleaning depthmap for image DJI_0052.JPG
2017-03-10 13:48:55,157 Cleaning depthmap for image DJI_0228.JPG
2017-03-10 13:48:56,464 Cleaning depthmap for image DJI_0087.JPG
2017-03-10 13:48:57,821 Cleaning depthmap for image DJI_0124.JPG
2017-03-10 13:48:59,103 Cleaning depthmap for image DJI_0118.JPG
2017-03-10 13:49:00,459 Cleaning depthmap for image DJI_0079.JPG
2017-03-10 13:49:01,845 Cleaning depthmap for image DJI_0241.JPG
2017-03-10 13:49:06,852 Cleaning depthmap for image DJI_0051.JPG
2017-03-10 13:49:08,309 Merging depthmaps
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/code/run.py", line 55, in <module>
    plasm.execute(niter=1)
  File "/code/scripts/opensfm.py", line 90, in process
    (context.pyopencv_path, context.opensfm_path, tree.opensfm))
  File "/code/opendm/system.py", line 28, in run
    raise Exception("Child returned {}".format(retcode))
Exception: Child returned 139
```

Any ideas?  I'm fairly new to the project and I'm not sure where to dig in.

**Comment by jkbonfield** [comment]
You added an issue to the wrong project!  Sorry.

**Comment by bstempi** [comment]
Hahaha, that' embarrassing!  Sorry, I was switching between tabs and I guess I pasted in the wrong one.
